name: pyjama_runner
description: a p2e game for pyjama token on solana

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flame: 1.18.0
  flame_audio: 2.10.2
  hive: 2.2.3
  path_provider: 2.1.3
  provider: 6.1.2
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8

dev_dependencies:
  hive_generator: 2.0.1
  build_runner: 2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/parallax/
    - assets/images/parallax/new/
    - assets/images/AngryPig/
    - assets/images/Bat/
    - assets/images/Rino/
    - assets/images/pyjama/
    - assets/images/pyjama/characters/
    - assets/images/pyjama/activities/
    - assets/images/pyjama/modes/
    - assets/images/pyjama/tasks/
    - assets/icons/
    - assets/icons/navigation/
    - assets/icons/profile/
    - assets/audio/

  fonts:
    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide/Audiowide-Regular.ttf
