name: pyjamaapp
description: a p2e game for pyjama token on solana

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  app_links: ^6.3.2
  cloud_firestore: ^5.4.4
  crypto: ^3.0.6
  cryptography: ^2.7.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  flame: ^1.21.0
  flame_audio: ^2.10.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  go_router: ^14.3.0
  hive: ^2.2.3
  path_provider: ^2.1.4
  pinenacl: ^0.6.0
  provider: ^6.1.2
  share_plus: ^10.1.0
  solana: ^0.31.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  hive_generator: 2.0.1
  mews_pedantic: ^0.32.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/icons/
    - assets/icons/profile/
    - assets/icons/navigation/
    - assets/images/app/
    - assets/images/pyjama/
    - assets/images/brick_breaker/
    - assets/images/fruit_ninja/
    - assets/images/pyjama/parallax/
    - assets/images/pyjama/parallax/new/
    - assets/images/pyjama/AngryPig/
    - assets/images/pyjama/Bat/
    - assets/images/pyjama/Rino/
    - assets/images/pyjama/characters/
    - assets/images/pyjama/activities/
    - assets/images/pyjama/modes/
    - assets/images/pyjama/tasks/
    - assets/audio/brick_breaker/
    - assets/audio/fruit_ninja/
    - assets/audio/pyjama/

  fonts:
    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide/Audiowide-Regular.ttf
